name: Dependabot Version Bump

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  bump-version:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc

      - name: Check if version already bumped
        id: version-check
        uses: ./.github/actions/check-version-changed
        with:
          base-ref: origin/main

      - name: Fail if version not bumped
        if: steps.version-check.outputs.changed == 'false'
        run: |
          echo "::error::This Dependabot PR does not include a version bump. Please create a changeset and bump the version before merging so a new version of the package is generated."
          echo "Check https://github.com/govuk-one-login/data-npm/blob/main/README.md on how to create a changeset and release a new version of the package."

